### ISSUE TITLE
Is tokio-serde-json concurrency safe?

### ISSUE THREAD

**Issue by joshlf** [carllerche/tokio-serde-json#10]
If I have two outstanding futures resulting from calls to [`WriteJson`](https://carllerche.github.io/tokio-serde-json/tokio_serde_json/struct.WriteJson.html)`::send`, am I guaranteed that the bytes that are written as a result of those calls will not be interleaved? What about for two outstanding futures resulting from calls to [`ReadJson`](https://carllerche.github.io/tokio-serde-json/tokio_serde_json/struct.ReadJson.html)`::into_future`?

Looking through the source code, I *think* that the use of `tokio_serde::FramedXXX` provides this guarantee, but I'm not sure. Either way, it'd be good for that guarantee (or the lack of guarantee, and thus the risk that you take by having multiple outstanding requests) to be documented both here and in `tokio_serde`.

**Comment by carllerche** [comment]
Order should be maintained. I would take a doc PR clarifying this.

I will close the issue, but we can continue discussing if you have further questions.
